from enum import Enum


class JobStatus(str, Enum):
    RECEIVED = "RECEIVED"
    SECURITY_CHECK = "SECURITY_CHECK"
    IDENTIFIED = "IDENTIFIED"
    EXTRACTING = "EXTRACTING"
    NORMALIZING = "NORMALIZING"
    VALIDATING = "VALIDATING"
    COMPARING = "COMPARING"
    STAGED = "STAGED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    COMMITTING = "COMMITTING"
    EXPORTING = "EXPORTING"
    PUBLISHING = "PUBLISHING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    QUARANTINED = "QUARANTINED"
    ROLLED_BACK = "ROLLED_BACK"


_ALLOWED = {
    "RECEIVED": {"SECURITY_CHECK", "FAILED", "CANCELLED"},
    "SECURITY_CHECK": {"IDENTIFIED", "FAILED", "QUARANTINED"},
    "IDENTIFIED": {"EXTRACTING", "REVIEW_REQUIRED", "FAILED"},
    "EXTRACTING": {"NORMALIZING", "FAILED", "QUARANTINED", "CANCELLED"},
    "NORMALIZING": {"VALIDATING", "FAILED", "CANCELLED"},
    "VALIDATING": {"COMPARING", "REVIEW_REQUIRED", "FAILED", "QUARANTINED", "CANCELLED"},
    "COMPARING": {"STAGED", "REVIEW_REQUIRED", "FAILED", "CANCELLED"},
    "STAGED": {"APPROVED", "REVIEW_REQUIRED", "FAILED"},
    "REVIEW_REQUIRED": {"APPROVED", "CANCELLED", "QUARANTINED"},
    "APPROVED": {"COMMITTING", "CANCELLED"},
    "COMMITTING": {"EXPORTING", "FAILED", "ROLLED_BACK"},
    "EXPORTING": {"PUBLISHING", "FAILED", "ROLLED_BACK"},
    "PUBLISHING": {"VERIFYING", "FAILED", "ROLLED_BACK"},
    "VERIFYING": {"COMPLETED", "FAILED", "ROLLED_BACK"},
}

TERMINAL_STATUSES = {
    JobStatus.COMPLETED.value,
    JobStatus.FAILED.value,
    JobStatus.CANCELLED.value,
    JobStatus.QUARANTINED.value,
    JobStatus.ROLLED_BACK.value,
}


def can_transition(current, target):
    current_value = getattr(current, "value", current)
    return target in _ALLOWED.get(current_value, set())
